/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import modelo.planificacionDTO.Archivo;

/**
 *
 * @author Luis Reategui
 */
public class FArchivo extends javax.swing.JPanel {

    Archivo archivo;

    /**
     * Creates new form Docuemnto
     *
     * @param archivoImp el objeto que contiene los datos del archivo a
     * visualizat en el grid del repositorio
     */
    public FArchivo(Archivo archivoImp) {
        initComponents();
        //CONFIGURACION DEL FRAME
        
        archivo = archivoImp;

        txtTitulo.setText(archivo.getTitulo() + "." + archivo.getExtension());
        lblImagen.setIcon(new ImageIcon(getClass().getResource(archivo.getImagen())));
        //para presentar un detalle del nombre del archivo, cuando se pase el puntero sobre el objeto
        setToolTipText(archivo.getTitulo());
    }

    public FArchivo() {
    }

    public void setImagen(String imagen) {
        lblImagen.setIcon(new ImageIcon(getClass().getResource(imagen)));
    }

    public Archivo getArchivo() {
        return archivo;
    }

    public void setArchivo(Archivo archivo) {
        this.archivo = archivo;
    }

    public JLabel getLblImagen() {
        return lblImagen;
    }

    public void setLblImagen(JLabel lblImagen) {
        this.lblImagen = lblImagen;
    }

    public JTextPane getTxtTitulo() {
        return txtTitulo;
    }

    public void setTxtTitulo(JTextPane txtTitulo) {
        this.txtTitulo = txtTitulo;
    }

    public JCheckBox getChkSeleccinado() {
        return chkSeleccinado;
    }

    public void setChkSeleccinado(JCheckBox chkSeleccinado) {
        this.chkSeleccinado = chkSeleccinado;
    }

    public boolean isSeleccionado(){
        return chkSeleccinado.isSelected();
    }
    
    public void setSeleccionado(boolean activar){
        chkSeleccinado.setSelected(activar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextPane();
        chkSeleccinado = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no38.PNG"))); // NOI18N

        txtTitulo.setEditable(false);
        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTitulo.setText("Título");
        txtTitulo.setAutoscrolls(false);
        txtTitulo.setOpaque(false);

        chkSeleccinado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSeleccinadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(chkSeleccinado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(chkSeleccinado))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(new Color(243, 255, 255));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.setBackground(new Color(150, 200, 255));
        if(isSeleccionado()){
            setSeleccionado(false);
        }else{
            setSeleccionado(true);
        }
    }//GEN-LAST:event_formMouseClicked

    private void chkSeleccinadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSeleccinadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSeleccinadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkSeleccinado;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextPane txtTitulo;
    // End of variables declaration//GEN-END:variables

}
