/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ricky
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private static Principal me;
    private static FRLogin venLogJefPla = null;

    private Principal() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    //CONFIGURAR EL ICONO DEL JFRAME REPOSITORIO
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("images/Logo-UG.png"));
        return retValue;
    }

    public static Principal getFrame() {
        if (me == null) {
            me = new Principal();
        }
        return me;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        pbl_principal = new javax.swing.JPanel();
        btnBodega = new javax.swing.JButton();
        btnPlanificacion = new javax.swing.JButton();
        btnInfraestructura = new javax.swing.JButton();
        btnFiscalizacion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnDireccion = new javax.swing.JButton();
        lbIconoUG = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PLAN PILOTO DE GESTION DE ARCHIVOS Y SEGUIMIENTO DE PROCESOS");
        setForeground(java.awt.Color.white);
        setIconImage(getIconImage());
        setLocation(new java.awt.Point(50, 50));

        pbl_principal.setBackground(new java.awt.Color(0, 102, 255));

        btnBodega.setBackground(new java.awt.Color(255, 255, 255));
        btnBodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Inventario3_1.png"))); // NOI18N
        btnBodega.setText("BODEGA");
        btnBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBodegaActionPerformed(evt);
            }
        });

        btnPlanificacion.setBackground(new java.awt.Color(255, 255, 255));
        btnPlanificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plan.png"))); // NOI18N
        btnPlanificacion.setText("JEFATURA \nDE PLANIFICACION\n\n");
        btnPlanificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanificacionActionPerformed(evt);
            }
        });

        btnInfraestructura.setBackground(new java.awt.Color(255, 255, 255));
        btnInfraestructura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/infra.png"))); // NOI18N
        btnInfraestructura.setText("JEFATURA DE INFRAESTRUCTURA");

        btnFiscalizacion.setBackground(new java.awt.Color(255, 255, 255));
        btnFiscalizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fisc.png"))); // NOI18N
        btnFiscalizacion.setText("JEFATURA DE FISCALIZACION");

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnDireccion.setBackground(new java.awt.Color(255, 255, 255));
        btnDireccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grupo.png"))); // NOI18N
        btnDireccion.setText("DIRECCIÓN D.I.O.U.");

        lbIconoUG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconoUG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo-UG.png"))); // NOI18N
        lbIconoUG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("SISTEMA INTERNO DE OBRAS UNIVERSITARIAS UG");

        javax.swing.GroupLayout pbl_principalLayout = new javax.swing.GroupLayout(pbl_principal);
        pbl_principal.setLayout(pbl_principalLayout);
        pbl_principalLayout.setHorizontalGroup(
            pbl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbl_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pbl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pbl_principalLayout.createSequentialGroup()
                        .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pbl_principalLayout.createSequentialGroup()
                        .addGroup(pbl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pbl_principalLayout.createSequentialGroup()
                                .addGroup(pbl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnInfraestructura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBodega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbIconoUG, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pbl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnFiscalizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPlanificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pbl_principalLayout.createSequentialGroup()
                                .addComponent(btnDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175)
                                .addComponent(btnSalir)))
                        .addGap(10, 10, 10))))
        );

        pbl_principalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBodega, btnDireccion, btnFiscalizacion, btnInfraestructura, btnPlanificacion});

        pbl_principalLayout.setVerticalGroup(
            pbl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbl_principalLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pbl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pbl_principalLayout.createSequentialGroup()
                        .addGroup(pbl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFiscalizacion)
                            .addComponent(btnInfraestructura, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pbl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlanificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBodega, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(lbIconoUG, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(pbl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDireccion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40))
        );

        btnPlanificacion.getAccessibleContext().setAccessibleName("plan  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pbl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pbl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBodegaActionPerformed
        // TODO add your handling code here:
        Bodega bod = new Bodega();
        bod.setVisible(true);
    }//GEN-LAST:event_btnBodegaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Principal p = Principal.getFrame();
        p.setVisible(false);
        p.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnPlanificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanificacionActionPerformed
        if (venLogJefPla == null) {
            try {
                venLogJefPla = new FRLogin(this, false);
                venLogJefPla.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            venLogJefPla.setVisible(true);
        }
    }//GEN-LAST:event_btnPlanificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBodega;
    private javax.swing.JButton btnDireccion;
    private javax.swing.JButton btnFiscalizacion;
    private javax.swing.JButton btnInfraestructura;
    private javax.swing.JButton btnPlanificacion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lbIconoUG;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pbl_principal;
    // End of variables declaration//GEN-END:variables
}
