/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogos;

import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author Luis Reategui
 */
public class Dialogo extends javax.swing.JDialog {

    /**
     * Creates new form DialogoConfirmacion
     */
    public Dialogo(JFrame parent) {
        super(parent, true);
        setLocationRelativeTo(null);
        setResizable(false);
        initComponents();
    }

    public void mostrarCuadroInformacion(JDialog parent, String titulo, String texto) {
        setTitle(titulo);
        getContentPane().removeAll();
        add(new PnlInformacion());
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    public void mostrarCuadroConfirmacion(JDialog parent, String titulo, String texto) {
        setTitle(titulo);
        getContentPane().removeAll();
        add(new PnlConfirmacion());
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(361, 197));
        setMinimumSize(new java.awt.Dimension(361, 197));
        setPreferredSize(new java.awt.Dimension(340, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
