/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogos;

/**
 *
 * @author Luis Reategui
 */
public class PnlConfirmacion extends javax.swing.JPanel {

    /**
     * Creates new form PnlConfirmacion
     */
    public PnlConfirmacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConfirmacion = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lbConfTexto = new javax.swing.JLabel();
        btnConfSI = new rojeru_san.RSButton();
        btnConfNO = new rojeru_san.RSButton();

        pnlConfirmacion.setBackground(new java.awt.Color(0, 102, 255));
        pnlConfirmacion.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlConfirmacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoUG32.png"))); // NOI18N

        lbConfTexto.setForeground(new java.awt.Color(255, 255, 255));
        lbConfTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbConfTexto.setText("Información");
        lbConfTexto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnConfSI.setBackground(new java.awt.Color(255, 255, 255));
        btnConfSI.setForeground(new java.awt.Color(0, 112, 192));
        btnConfSI.setText("SI");
        btnConfSI.setColorText(new java.awt.Color(0, 112, 192));
        btnConfSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfSIActionPerformed(evt);
            }
        });

        btnConfNO.setBackground(new java.awt.Color(255, 255, 255));
        btnConfNO.setForeground(new java.awt.Color(0, 112, 192));
        btnConfNO.setText("NO");
        btnConfNO.setColorText(new java.awt.Color(0, 112, 192));
        btnConfNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfNOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConfirmacionLayout = new javax.swing.GroupLayout(pnlConfirmacion);
        pnlConfirmacion.setLayout(pnlConfirmacionLayout);
        pnlConfirmacionLayout.setHorizontalGroup(
            pnlConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConfirmacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfSI, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnConfNO, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConfirmacionLayout.createSequentialGroup()
                .addGroup(pnlConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlConfirmacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbConfTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlConfirmacionLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlConfirmacionLayout.setVerticalGroup(
            pnlConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfirmacionLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbConfTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfSIActionPerformed
 
    }//GEN-LAST:event_btnConfSIActionPerformed

    private void btnConfNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfNOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnConfNO;
    private rojeru_san.RSButton btnConfSI;
    private javax.swing.JLabel lbConfTexto;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JPanel pnlConfirmacion;
    // End of variables declaration//GEN-END:variables
}
